name: Run My Shell Script on Windows

on: [push]

jobs:
  run-my-shell-script:
    runs-on: windows-latest  # Switch to Windows container

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Set up Lua
      run: |
        # Install Lua 5.3 on Windows
        choco install lua53

        set PATH=%PATH%;C:\ProgramData\chocolatey\lib\lua53\tools
        refreshenv
        
        # Confirm Lua is installed
        lua -v

    - name: Run the shell script
      run: .github/workflows/action.bat  # Call the Windows batch script instead of a .sh file
