name: Run My Shell Script

on: [push]

jobs:
  run-my-shell-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@dev

    - name: Run the shell script
      run: action.sh
