# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: set up environment
        shell: cmd
        run: |
          @echo off
          set LUA_VERSION=5.3.6
          set LUA_INSTALL_DIR = c:\Lua\lua-%LUA_VERSION%
          echo Downloading Lua...
          curl -L -o lua-%LUA_VERSION%.tar.gz https://www.lua.org/ftp/lua-%LUA_VERSION%.tar.gz
          echo Extracting Lua...
          tar -xvf lua-%LUA_VERSION%.tar.gz
          echo Installing Lua...
          if not exist %LUA_INSTALL_DIR% (mkdir %LUA_INSTALL_DIR% 2>nul if not errorlevel 1 ( move lua-%LUA_VERSION% C:\Lua))
          set PATH "%PATH%;%LUA_INSTALL_DIR%"
          echo Cleaning up...
          del lua-%LUA_VERSION%.tar.gz
          echo Downloading Luarocks...
          curl -L -o luarocks-3.11.1.zip https://luarocks.github.io/luarocks/releases/luarocks-3.11.1-win32.zip
          echo Extracting Luarocks...
          set LUAROCKS_INSTALL_DIR = C:\Luarocks
          tar -xvf luarocks-3.11.1.zip
          cd luarocks-3.11.1-win32
          echo Installing Luarocks...
          install.bat /P %LUAROCKS_INSTALL_DIR% /SELFCONTAINED /LV 5.3 /LUA %LUA_INSTALL_DIR% /MW /NOADMIN /Q
          echo Cleaning up...
          cd..
          del luarocks-3.11.1.zip
          echo Installing Git...
          winget install Git.Git
          set %REPO_HOME% C:\Mach4
          cd c:
          echo Cloning source repository...
          git clone https://github.com/podrybaum/mach4.git -b dev
          set COMPILER_INSTALL_DIR = C:\Compilers
          if not exist %COMPILER_INSTALL_DIR% (mkdir %COMPILER_INSTALL_DIR%)
          echo Downloading C compilers...
          curl -L -o mingw.zip https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-ucrt-r2/winlibs-i686-posix-dwarf-gcc-14.2.0-llvm-19.1.1-mingw-w64ucrt-12.0.0-r2.zip
          echo Extracing C compilers...
          tar -xvf mingw.zip -C %COMPILER_INSTALL_DIR%
          set CC=%COMPILER_INSTALL_DIR%/mingw32/bin/i686-w64-mingw32-gcc.exe
          luarocks install luasrcdiet
          
